name: openalea
channels:
  - openalea3
  - conda-forge

dependencies:
  - python
  - openalea.plantgl
  - openalea.core
  - openalea.mtg
  - sphinxcontrib-napoleon
  - myst-parser
  - pydata-sphinx-theme
  - sphinx-favicon
  - sphinx-copybutton
